name: UPDATE JSON FILE V1.0

on:
  push:
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run apps.json generator script
        run: |
          chmod +x path_01.sh
          ./path_01.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Commit and push apps.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add apps.json
          git diff --cached --quiet || git commit -m "Auto-generate apps.json"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
